name: ti-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=2.0.1
  - importlib-metadata=7.2.1
  - importlib_metadata=7.2.1
  - ipykernel=6.29.4
  - ipython=8.25.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.3.1
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.10.14
  - python_abi=3.10
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alembic==1.13.1
      - anndata==0.10.7
      - antlr4-python3-runtime==4.9.3
      - array-api-compat==1.7.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - autopage==0.5.2
      - black==24.4.2
      - certifi==2024.6.2
      - cfgv==3.4.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cliff==4.7.0
      - cloudpickle==3.0.0
      - cmaes==0.10.0
      - cmd2==2.4.3
      - colorlog==6.8.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - distlib==0.3.8
      - docker-pycreds==0.4.0
      - exceptiongroup==1.2.1
      - filelock==3.15.1
      - fire==0.6.0
      - flake8==7.0.0
      - flake8-pyproject==1.2.3
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - greenlet==3.0.3
      - h5py==3.11.0
      - huggingface-hub==0.23.4
      - hydra-colorlog==1.2.0
      - hydra-core==1.2.0
      - hydra-optuna-sweeper==1.2.0
      - hydra-submitit-launcher==1.2.0
      - identify==2.5.36
      - idna==3.7
      - iniconfig==2.0.0
      - ipywidgets==8.1.3
      - isort==5.13.2
      - joblib==1.4.2
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - legacy-api-wrap==1.4
      - lightning-bolts==0.6.0.post1
      - lightning-utilities==0.3.0
      - llvmlite==0.43.0
      - mako==1.3.5
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - mccabe==0.7.0
      - mdurl==0.1.2
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - natsort==8.4.0
      - networkx==3.3
      - nodeenv==1.9.1
      - numba==0.60.0
      - numpy==1.26.4
      - omegaconf==2.3.0
      - optuna==2.10.1
      - pandas==2.0.3
      - pastel==0.2.1
      - pathspec==0.12.1
      - patsy==0.5.6
      - pbr==6.0.0
      - pillow==10.3.0
      - pluggy==1.5.0
      - poethepoet==0.10.0
      - pot==0.9.3
      - pre-commit==3.7.1
      - prettytable==3.10.0
      - protobuf==5.27.1
      - psutil==5.9.8
      - pycodestyle==2.11.1
      - pyflakes==3.2.0
      - pynndescent==0.5.12
      - pyparsing==3.1.2
      - pyperclip==1.8.2
      - pyrootutils==1.0.4
      - pytest==8.2.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      # - python-graphviz==0.20.3
      - pytorch-lightning==1.8.3
      - pytz==2024.1
      - pyyaml==6.0.1
      - requests==2.32.3
      - rich==13.7.1
      - safetensors==0.4.3
      - scanpy==1.10.1
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - scprep==1.2.3
      - seaborn==0.13.2
      - sentry-sdk==2.5.1
      - session-info==1.0.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sqlalchemy==2.0.30
      - statsmodels==0.14.2
      - stdlib-list==0.10.0
      - stevedore==5.2.0
      - submitit==1.5.1
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - timm==1.0.3
      - tomli==2.0.1
      - tomlkit==0.12.5
      - torch==1.12.1+cu113
      - torchaudio==0.12.1+cu113
      - torchcde==0.2.5
      # - torchcubicspline==0.0.3
      - torchdiffeq==0.2.4
      - torchdyn==1.0.6
      - torchmetrics==0.11.0
      - torchsde==0.2.6
      - torchvision==0.13.1+cu113
      - torchviz==0.0.2
      - tqdm==4.66.4
      - trampoline==0.1.2
      - tzdata==2024.1
      - umap-learn==0.5.6
      - urllib3==2.2.1
      - virtualenv==20.26.2
      - wandb==0.17.1
      - widgetsnbextension==4.0.11
      - yarl==1.9.4
