# @package _global_
model_module:
  _target_: model.cfm_baseline.MLP_CFM
  time_varying: true
  conditional: true
  treatment_cond: 0
  clip: 1e-2
  sigma: 0.1
  dim: 2
  metrics:
    - variance_dist
    - mse_loss
    - l1_loss