# @package _global_
model_module:
  _target_: model.FM_baseline.MLP_FM
  time_varying: true
  conditional: false
  treatment_cond: 0
  clip: 1e-2
  sigma: 0.1
  dim: 2
  metrics:
    - variance_dist
    - mse_loss
    - l1_loss