# @package _global_
model_module:
  _target_: model.mlp_memory.MLP_Cond_Memory_Module
  time_varying: true
  conditional: true
  treatment_cond: 0
  memory: 3
  w: 256 
  clip: 1e-2
  sigma: 0.1
  dim: 2
  metrics:
    - variance_dist
    - mse_loss
    - l1_loss
